name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build app and run unit tests
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease testReleaseUnitTest
